### ISSUE TITLE
ASIH to recordset CSV

### ISSUE THREAD

**Issue by kevinlove** [melanostomias/rstuff#1]
Looks like we have duplicates:

rstuff/vocab/ASIH_Codes_UUID.csv

MNHN
KU

How do you want to handle these?

**Comment by melanostomias** [comment]
?They are the same collection but two recordsets

**Comment by kevinlove** [comment]
I understand that, how would you like to approach the data?

Should we:

A. Concatenate the recordsets
B. Concatenate the recordsets and do some basic duplicate detection (maybe catalog number?)
C. Some other procedure to handle two recordsets from the same collection

**Comment by kevinlove** [comment]
We decided to simply concatenate recordsets.
