### ISSUE TITLE
More collections

### ISSUE THREAD

**Issue by kevinlove** [melanostomias/rstuff#9]
ASIHCode|recordset_uuid|collection_uuid | logo|collection_description|name
-----|------|------|------|------|------
SIO | d56c787a-7da2-438b-81c5-554442f97259| | | |SIO Marine Vertebrate Collection
USNM | a6eee223-cf3b-4079-8bb2-b77dad8cae9d| | | |NMNH Extant Specimen and Observation Records
UWZM |295a8445-346f-4ea2-b0cf-4a3863c72cdb| | | |university of wisconsin-madison zoological museum - fish
UMMZ |75c7a013-8dab-4f9c-ae6d-3a7cc24b67ce| | | |university of michigan museum of zoology - fish
UTEP |3c6099e4-3a0c-44c8-942a-f44860aea12b| | | |utep fish (arctos)
ANWC |02153e3c-902f-4d8d-8c7a-11c38b99ec0c| | | |csiro ichthyology provider for ozcam
MMNS |6aa085c5-7abf-4995-a3fc-91c49ad65b79| | |The Ichthyology Collection is the largest of the biological collections housed at MMNS with the earliest material dating back to 1888. The majority of the holdings represent freshwater species; however, the collection does contain representative material from marine and estuarine habitats.  |mmns ichthyology collection
KUIT |0f53b3e3-c248-4026-a070-15c3fefdbbc0| | | |kubi ichthyology tissue collection

**Comment by kevinlove** [comment]
http://jupyter.idigbio.org/user/kevinlove/tree/log

**Comment by kevinlove** [comment]
@melanostomias , we need to get these collections added to this file:

https://github.com/melanostomias/rstuff/blob/master/vocab/ASIH_Codes_UUID.csv

Let me know if you need help with the process, should be as easy as editing the spreadsheet and assigning ASIH code, collection description, logo url

**Comment by kevinlove** [comment]
@melanostomias I added the codes as I think they fit, can you take a look and see if they square up? I'll update the vocab file with these stub records if they are correct and continue on with adding these collections to our data collection

**Comment by melanostomias** [comment]
UTEP, ANWC, are international and I need to check MMNS and KUIT. 

UMMZ, USNM, SIO, UWZM are all US Collections

**Comment by kevinlove** [comment]
Excludes: KUIT, ANWC

**Comment by kevinlove** [comment]
Closing this issue, as new collections are found, they are logged here: https://github.com/melanostomias/rstuff/tree/master/log
